/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gateway.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gateway.pb-c.h"
void   proto__uplink_frame__init
                     (Proto__UplinkFrame         *message)
{
  static const Proto__UplinkFrame init_value = PROTO__UPLINK_FRAME__INIT;
  *message = init_value;
}
size_t proto__uplink_frame__get_packed_size
                     (const Proto__UplinkFrame *message)
{
  assert(message->base.descriptor == &proto__uplink_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__uplink_frame__pack
                     (const Proto__UplinkFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__uplink_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__uplink_frame__pack_to_buffer
                     (const Proto__UplinkFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__uplink_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__UplinkFrame *
       proto__uplink_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__UplinkFrame *)
     protobuf_c_message_unpack (&proto__uplink_frame__descriptor,
                                allocator, len, data);
}
void   proto__uplink_frame__free_unpacked
                     (Proto__UplinkFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__uplink_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__downlink_frame__init
                     (Proto__DownlinkFrame         *message)
{
  static const Proto__DownlinkFrame init_value = PROTO__DOWNLINK_FRAME__INIT;
  *message = init_value;
}
size_t proto__downlink_frame__get_packed_size
                     (const Proto__DownlinkFrame *message)
{
  assert(message->base.descriptor == &proto__downlink_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__downlink_frame__pack
                     (const Proto__DownlinkFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__downlink_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__downlink_frame__pack_to_buffer
                     (const Proto__DownlinkFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__downlink_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__DownlinkFrame *
       proto__downlink_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__DownlinkFrame *)
     protobuf_c_message_unpack (&proto__downlink_frame__descriptor,
                                allocator, len, data);
}
void   proto__downlink_frame__free_unpacked
                     (Proto__DownlinkFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__downlink_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__payload__init
                     (Proto__Payload         *message)
{
  static const Proto__Payload init_value = PROTO__PAYLOAD__INIT;
  *message = init_value;
}
size_t proto__payload__get_packed_size
                     (const Proto__Payload *message)
{
  assert(message->base.descriptor == &proto__payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__payload__pack
                     (const Proto__Payload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__payload__pack_to_buffer
                     (const Proto__Payload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__Payload *
       proto__payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__Payload *)
     protobuf_c_message_unpack (&proto__payload__descriptor,
                                allocator, len, data);
}
void   proto__payload__free_unpacked
                     (Proto__Payload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__uplink_frame__field_descriptors[7] =
{
  {
    "FrameType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Proto__UplinkFrame, frametype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DevName",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__UplinkFrame, devname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DevId",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__UplinkFrame, devid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FrameNum",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__UplinkFrame, framenum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Port",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__UplinkFrame, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PhyPayload",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__UplinkFrame, phypayload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "UplinkId",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__UplinkFrame, uplinkid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__uplink_frame__field_indices_by_name[] = {
  2,   /* field[2] = DevId */
  1,   /* field[1] = DevName */
  3,   /* field[3] = FrameNum */
  0,   /* field[0] = FrameType */
  5,   /* field[5] = PhyPayload */
  4,   /* field[4] = Port */
  6,   /* field[6] = UplinkId */
};
static const ProtobufCIntRange proto__uplink_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor proto__uplink_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.UplinkFrame",
  "UplinkFrame",
  "Proto__UplinkFrame",
  "proto",
  sizeof(Proto__UplinkFrame),
  7,
  proto__uplink_frame__field_descriptors,
  proto__uplink_frame__field_indices_by_name,
  1,  proto__uplink_frame__number_ranges,
  (ProtobufCMessageInit) proto__uplink_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__downlink_frame__field_descriptors[7] =
{
  {
    "FrameType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Proto__DownlinkFrame, frametype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DevName",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__DownlinkFrame, devname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DevId",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__DownlinkFrame, devid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FrameNum",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__DownlinkFrame, framenum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Port",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__DownlinkFrame, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PhyPayload",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__DownlinkFrame, phypayload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DownlinkId",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__DownlinkFrame, downlinkid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__downlink_frame__field_indices_by_name[] = {
  2,   /* field[2] = DevId */
  1,   /* field[1] = DevName */
  6,   /* field[6] = DownlinkId */
  3,   /* field[3] = FrameNum */
  0,   /* field[0] = FrameType */
  5,   /* field[5] = PhyPayload */
  4,   /* field[4] = Port */
};
static const ProtobufCIntRange proto__downlink_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor proto__downlink_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.DownlinkFrame",
  "DownlinkFrame",
  "Proto__DownlinkFrame",
  "proto",
  sizeof(Proto__DownlinkFrame),
  7,
  proto__downlink_frame__field_descriptors,
  proto__downlink_frame__field_indices_by_name,
  1,  proto__downlink_frame__number_ranges,
  (ProtobufCMessageInit) proto__downlink_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__payload__field_descriptors[3] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__Payload, kind),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__Payload, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__Payload, val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__payload__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = kind */
  2,   /* field[2] = val */
};
static const ProtobufCIntRange proto__payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.Payload",
  "Payload",
  "Proto__Payload",
  "proto",
  sizeof(Proto__Payload),
  3,
  proto__payload__field_descriptors,
  proto__payload__field_indices_by_name,
  1,  proto__payload__number_ranges,
  (ProtobufCMessageInit) proto__payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue proto__category__enum_values_by_number[2] =
{
  { "CMD", "PROTO__CATEGORY__CMD", 0 },
  { "CONFIG", "PROTO__CATEGORY__CONFIG", 1 },
};
static const ProtobufCIntRange proto__category__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex proto__category__enum_values_by_name[2] =
{
  { "CMD", 0 },
  { "CONFIG", 1 },
};
const ProtobufCEnumDescriptor proto__category__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "proto.Category",
  "Category",
  "Proto__Category",
  "proto",
  2,
  proto__category__enum_values_by_number,
  2,
  proto__category__enum_values_by_name,
  1,
  proto__category__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue proto__device__enum_values_by_number[2] =
{
  { "LAMP", "PROTO__DEVICE__LAMP", 0 },
  { "HEATER", "PROTO__DEVICE__HEATER", 1 },
};
static const ProtobufCIntRange proto__device__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex proto__device__enum_values_by_name[2] =
{
  { "HEATER", 1 },
  { "LAMP", 0 },
};
const ProtobufCEnumDescriptor proto__device__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "proto.Device",
  "Device",
  "Proto__Device",
  "proto",
  2,
  proto__device__enum_values_by_number,
  2,
  proto__device__enum_values_by_name,
  1,
  proto__device__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue proto__operation__enum_values_by_number[2] =
{
  { "OFF", "PROTO__OPERATION__OFF", 0 },
  { "ON", "PROTO__OPERATION__ON", 1 },
};
static const ProtobufCIntRange proto__operation__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex proto__operation__enum_values_by_name[2] =
{
  { "OFF", 0 },
  { "ON", 1 },
};
const ProtobufCEnumDescriptor proto__operation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "proto.Operation",
  "Operation",
  "Proto__Operation",
  "proto",
  2,
  proto__operation__enum_values_by_number,
  2,
  proto__operation__enum_values_by_name,
  1,
  proto__operation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
