/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: parser.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "parser.grpc-c.h"

int
parser__parser__service_init (grpc_c_server_t *server)
{
    int ret = 0;
    ret |=grpc_c_register_method(server, parser__parser__methods[0], 
                          0, 0, parser__parser__marshal_cb,
                          &parser__parser__methods__funcs[0]);

    ret |=grpc_c_register_method(server, parser__parser__methods[1], 
                          0, 0, parser__parser__un_marshal_cb,
                          &parser__parser__methods__funcs[1]);

    return ret;
}
