/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: parser.proto */

#ifndef PROTOBUF_C_parser_2eproto__INCLUDED
#define PROTOBUF_C_parser_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

#include <grpc/grpc.h>
#include <grpc/byte_buffer_reader.h>
#include <grpc/support/alloc.h>
#include <grpc/support/log.h>
#include <grpc-c/grpc-c.h>

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Parser__DownReq Parser__DownReq;
typedef struct _Parser__DownReq parser__DownReq;
#define parser__DownReq__init parser__down_req__init
#define parser__DownReq__free_unpacked parser__down_req__free_unpacked
typedef struct _Parser__DownRsp Parser__DownRsp;
typedef struct _Parser__DownRsp parser__DownRsp;
#define parser__DownRsp__init parser__down_rsp__init
#define parser__DownRsp__free_unpacked parser__down_rsp__free_unpacked
typedef struct _Parser__UpReq Parser__UpReq;
typedef struct _Parser__UpReq parser__UpReq;
#define parser__UpReq__init parser__up_req__init
#define parser__UpReq__free_unpacked parser__up_req__free_unpacked
typedef struct _Parser__UpRsp Parser__UpRsp;
typedef struct _Parser__UpRsp parser__UpRsp;
#define parser__UpRsp__init parser__up_rsp__init
#define parser__UpRsp__free_unpacked parser__up_rsp__free_unpacked


/* --- enums --- */


/* --- messages --- */

/*
 *客户端发送给服务端
 */
struct  _Parser__DownReq
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean has_payload;
  ProtobufCBinaryData payload;
};
#define PARSER__DOWN_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parser__down_req__descriptor) \
    , NULL, 0, {0,NULL} }


/*
 *服务端返回给客户端
 */
struct  _Parser__DownRsp
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean has_payload;
  ProtobufCBinaryData payload;
};
#define PARSER__DOWN_RSP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parser__down_rsp__descriptor) \
    , NULL, 0, {0,NULL} }


/*
 *客户端发送给服务端
 */
struct  _Parser__UpReq
{
  ProtobufCMessage base;
  char *id;
  char *name;
  protobuf_c_boolean has_payload;
  ProtobufCBinaryData payload;
  char *retain;
};
#define PARSER__UP_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parser__up_req__descriptor) \
    , NULL, NULL, 0, {0,NULL}, NULL }


/*
 *服务端返回给客户端
 */
struct  _Parser__UpRsp
{
  ProtobufCMessage base;
  char *id;
  char *name;
  protobuf_c_boolean has_payload;
  ProtobufCBinaryData payload;
  char *err;
};
#define PARSER__UP_RSP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&parser__up_rsp__descriptor) \
    , NULL, NULL, 0, {0,NULL}, NULL }


/* Parser__DownReq methods */
void   parser__down_req__init
                     (Parser__DownReq         *message);
size_t parser__down_req__get_packed_size
                     (const Parser__DownReq   *message);
size_t parser__down_req__pack
                     (const Parser__DownReq   *message,
                      uint8_t             *out);
size_t parser__down_req__pack_to_buffer
                     (const Parser__DownReq   *message,
                      ProtobufCBuffer     *buffer);
Parser__DownReq *
       parser__down_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parser__down_req__free_unpacked
                     (Parser__DownReq *message,
                      ProtobufCAllocator *allocator);
/* Parser__DownRsp methods */
void   parser__down_rsp__init
                     (Parser__DownRsp         *message);
size_t parser__down_rsp__get_packed_size
                     (const Parser__DownRsp   *message);
size_t parser__down_rsp__pack
                     (const Parser__DownRsp   *message,
                      uint8_t             *out);
size_t parser__down_rsp__pack_to_buffer
                     (const Parser__DownRsp   *message,
                      ProtobufCBuffer     *buffer);
Parser__DownRsp *
       parser__down_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parser__down_rsp__free_unpacked
                     (Parser__DownRsp *message,
                      ProtobufCAllocator *allocator);
/* Parser__UpReq methods */
void   parser__up_req__init
                     (Parser__UpReq         *message);
size_t parser__up_req__get_packed_size
                     (const Parser__UpReq   *message);
size_t parser__up_req__pack
                     (const Parser__UpReq   *message,
                      uint8_t             *out);
size_t parser__up_req__pack_to_buffer
                     (const Parser__UpReq   *message,
                      ProtobufCBuffer     *buffer);
Parser__UpReq *
       parser__up_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parser__up_req__free_unpacked
                     (Parser__UpReq *message,
                      ProtobufCAllocator *allocator);
/* Parser__UpRsp methods */
void   parser__up_rsp__init
                     (Parser__UpRsp         *message);
size_t parser__up_rsp__get_packed_size
                     (const Parser__UpRsp   *message);
size_t parser__up_rsp__pack
                     (const Parser__UpRsp   *message,
                      uint8_t             *out);
size_t parser__up_rsp__pack_to_buffer
                     (const Parser__UpRsp   *message,
                      ProtobufCBuffer     *buffer);
Parser__UpRsp *
       parser__up_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   parser__up_rsp__free_unpacked
                     (Parser__UpRsp *message,
                      ProtobufCAllocator *allocator);

/* --- data packers and unpackers -- */

/* parser__down_req packer and unpacker methods */
size_t parser__down_req_packer (void *input, grpc_byte_buffer **buffer);
void *parser__down_req_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer);
void parser__down_req_free (Parser__DownReq * buf);

/* parser__down_rsp packer and unpacker methods */
size_t parser__down_rsp_packer (void *input, grpc_byte_buffer **buffer);
void *parser__down_rsp_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer);
void parser__down_rsp_free (Parser__DownRsp * buf);

/* parser__up_req packer and unpacker methods */
size_t parser__up_req_packer (void *input, grpc_byte_buffer **buffer);
void *parser__up_req_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer);
void parser__up_req_free (Parser__UpReq * buf);

/* parser__up_rsp packer and unpacker methods */
size_t parser__up_rsp_packer (void *input, grpc_byte_buffer **buffer);
void *parser__up_rsp_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer);
void parser__up_rsp_free (Parser__UpRsp * buf);


/* --- services --- */

extern const char *parser__parser__methods[];

extern grpc_c_method_funcs_t parser__parser__methods__funcs[];

int parser__parser__service_init (grpc_c_server_t *server);

int parser__parser__marshal__sync(grpc_c_client_t *client, 
                                    grpc_c_metadata_array_t *array, uint32_t flags, 
                                    Parser__DownReq *input, Parser__DownRsp **output, 
                                    grpc_c_status_t *status, long timeout);

int parser__parser__marshal__async(grpc_c_client_t *client, 
                                     grpc_c_metadata_array_t *array, uint32_t flags, 
                                     Parser__DownReq *input, 
                                     grpc_c_client_callback_t *cb, void *tag, long timeout);

void parser__parser__marshal_cb (grpc_c_context_t *context);

int parser__parser__un_marshal__sync(grpc_c_client_t *client, 
                                       grpc_c_metadata_array_t *array, uint32_t flags, 
                                       Parser__UpReq *input, Parser__UpRsp **output, 
                                       grpc_c_status_t *status, long timeout);

int parser__parser__un_marshal__async(grpc_c_client_t *client, 
                                        grpc_c_metadata_array_t *array, uint32_t flags, 
                                        Parser__UpReq *input, 
                                        grpc_c_client_callback_t *cb, void *tag, long timeout);

void parser__parser__un_marshal_cb (grpc_c_context_t *context);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor parser__down_req__descriptor;
extern const ProtobufCMessageDescriptor parser__down_rsp__descriptor;
extern const ProtobufCMessageDescriptor parser__up_req__descriptor;
extern const ProtobufCMessageDescriptor parser__up_rsp__descriptor;



#endif  /* PROTOBUF_C_parser_2eproto__INCLUDED */
