/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: parser.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "parser.grpc-c.h"
void   parser__down_req__init
                     (Parser__DownReq         *message)
{
  static const Parser__DownReq init_value = PARSER__DOWN_REQ__INIT;
  *message = init_value;
}
size_t parser__down_req__get_packed_size
                     (const Parser__DownReq *message)
{
  assert(message->base.descriptor == &parser__down_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parser__down_req__pack
                     (const Parser__DownReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parser__down_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parser__down_req__pack_to_buffer
                     (const Parser__DownReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parser__down_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Parser__DownReq *
       parser__down_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Parser__DownReq *)
     protobuf_c_message_unpack (&parser__down_req__descriptor,
                                allocator, len, data);
}
void   parser__down_req__free_unpacked
                     (Parser__DownReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parser__down_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parser__down_rsp__init
                     (Parser__DownRsp         *message)
{
  static const Parser__DownRsp init_value = PARSER__DOWN_RSP__INIT;
  *message = init_value;
}
size_t parser__down_rsp__get_packed_size
                     (const Parser__DownRsp *message)
{
  assert(message->base.descriptor == &parser__down_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parser__down_rsp__pack
                     (const Parser__DownRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parser__down_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parser__down_rsp__pack_to_buffer
                     (const Parser__DownRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parser__down_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Parser__DownRsp *
       parser__down_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Parser__DownRsp *)
     protobuf_c_message_unpack (&parser__down_rsp__descriptor,
                                allocator, len, data);
}
void   parser__down_rsp__free_unpacked
                     (Parser__DownRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parser__down_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parser__up_req__init
                     (Parser__UpReq         *message)
{
  static const Parser__UpReq init_value = PARSER__UP_REQ__INIT;
  *message = init_value;
}
size_t parser__up_req__get_packed_size
                     (const Parser__UpReq *message)
{
  assert(message->base.descriptor == &parser__up_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parser__up_req__pack
                     (const Parser__UpReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parser__up_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parser__up_req__pack_to_buffer
                     (const Parser__UpReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parser__up_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Parser__UpReq *
       parser__up_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Parser__UpReq *)
     protobuf_c_message_unpack (&parser__up_req__descriptor,
                                allocator, len, data);
}
void   parser__up_req__free_unpacked
                     (Parser__UpReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parser__up_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parser__up_rsp__init
                     (Parser__UpRsp         *message)
{
  static const Parser__UpRsp init_value = PARSER__UP_RSP__INIT;
  *message = init_value;
}
size_t parser__up_rsp__get_packed_size
                     (const Parser__UpRsp *message)
{
  assert(message->base.descriptor == &parser__up_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parser__up_rsp__pack
                     (const Parser__UpRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parser__up_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parser__up_rsp__pack_to_buffer
                     (const Parser__UpRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parser__up_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Parser__UpRsp *
       parser__up_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Parser__UpRsp *)
     protobuf_c_message_unpack (&parser__up_rsp__descriptor,
                                allocator, len, data);
}
void   parser__up_rsp__free_unpacked
                     (Parser__UpRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parser__up_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor parser__down_req__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parser__DownReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Parser__DownReq, has_payload),
    offsetof(Parser__DownReq, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parser__down_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = payload */
};
static const ProtobufCIntRange parser__down_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parser__down_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "parser.DownReq",
  "DownReq",
  "Parser__DownReq",
  "parser",
  sizeof(Parser__DownReq),
  2,
  parser__down_req__field_descriptors,
  parser__down_req__field_indices_by_name,
  1,  parser__down_req__number_ranges,
  (ProtobufCMessageInit) parser__down_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parser__down_rsp__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parser__DownRsp, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Parser__DownRsp, has_payload),
    offsetof(Parser__DownRsp, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parser__down_rsp__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = payload */
};
static const ProtobufCIntRange parser__down_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parser__down_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "parser.DownRsp",
  "DownRsp",
  "Parser__DownRsp",
  "parser",
  sizeof(Parser__DownRsp),
  2,
  parser__down_rsp__field_descriptors,
  parser__down_rsp__field_indices_by_name,
  1,  parser__down_rsp__number_ranges,
  (ProtobufCMessageInit) parser__down_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parser__up_req__field_descriptors[4] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parser__UpReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parser__UpReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Parser__UpReq, has_payload),
    offsetof(Parser__UpReq, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retain",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parser__UpReq, retain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parser__up_req__field_indices_by_name[] = {
  0,   /* field[0] = ID */
  1,   /* field[1] = name */
  2,   /* field[2] = payload */
  3,   /* field[3] = retain */
};
static const ProtobufCIntRange parser__up_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor parser__up_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "parser.UpReq",
  "UpReq",
  "Parser__UpReq",
  "parser",
  sizeof(Parser__UpReq),
  4,
  parser__up_req__field_descriptors,
  parser__up_req__field_indices_by_name,
  1,  parser__up_req__number_ranges,
  (ProtobufCMessageInit) parser__up_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parser__up_rsp__field_descriptors[4] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parser__UpRsp, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parser__UpRsp, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Parser__UpRsp, has_payload),
    offsetof(Parser__UpRsp, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parser__UpRsp, err),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parser__up_rsp__field_indices_by_name[] = {
  0,   /* field[0] = ID */
  3,   /* field[3] = err */
  1,   /* field[1] = name */
  2,   /* field[2] = payload */
};
static const ProtobufCIntRange parser__up_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor parser__up_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "parser.UpRsp",
  "UpRsp",
  "Parser__UpRsp",
  "parser",
  sizeof(Parser__UpRsp),
  4,
  parser__up_rsp__field_descriptors,
  parser__up_rsp__field_indices_by_name,
  1,  parser__up_rsp__number_ranges,
  (ProtobufCMessageInit) parser__up_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};

size_t
parser__down_req_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = parser__down_req__get_packed_size((Parser__DownReq *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = parser__down_req__pack((Parser__DownReq *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
parser__down_req_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Parser__DownReq *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = parser__down_req__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void parser__down_req_free (Parser__DownReq * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    parser__down_req__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
parser__down_rsp_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = parser__down_rsp__get_packed_size((Parser__DownRsp *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = parser__down_rsp__pack((Parser__DownRsp *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
parser__down_rsp_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Parser__DownRsp *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = parser__down_rsp__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void parser__down_rsp_free (Parser__DownRsp * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    parser__down_rsp__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
parser__up_req_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = parser__up_req__get_packed_size((Parser__UpReq *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = parser__up_req__pack((Parser__UpReq *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
parser__up_req_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Parser__UpReq *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = parser__up_req__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void parser__up_req_free (Parser__UpReq * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    parser__up_req__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
parser__up_rsp_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = parser__up_rsp__get_packed_size((Parser__UpRsp *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = parser__up_rsp__pack((Parser__UpRsp *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
parser__up_rsp_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Parser__UpRsp *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = parser__up_rsp__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void parser__up_rsp_free (Parser__UpRsp * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    parser__up_rsp__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

const char *parser__parser__methods[] = {
    "/parser.Parser/Marshal",
    "/parser.Parser/UnMarshal",
};

grpc_c_method_funcs_t parser__parser__methods__funcs[] = {
    {parser__down_req_packer, parser__down_req_unpacker, parser__down_rsp_packer, parser__down_rsp_unpacker },
    {parser__up_req_packer, parser__up_req_unpacker, parser__up_rsp_packer, parser__up_rsp_unpacker },
};

int parser__parser__marshal__sync(grpc_c_client_t *client, 
                                    grpc_c_metadata_array_t *array, uint32_t flags, 
                                    Parser__DownReq *input, Parser__DownRsp **output, 
                                    grpc_c_status_t *status, long timeout)
{
    return grpc_c_client_request_sync(client, array, flags, parser__parser__methods[0], 
                                      (void *)input, (void **)output, status, 
                                      &parser__parser__methods__funcs[0], timeout);
}

int parser__parser__marshal__async(grpc_c_client_t *client, 
                                     grpc_c_metadata_array_t *array, uint32_t flags, 
                                     Parser__DownReq *input, 
                                     grpc_c_client_callback_t *cb, void *tag, long timeout)
{
    return grpc_c_client_request_async(client, array, flags, parser__parser__methods[0], 
                                       input, cb, tag, &parser__parser__methods__funcs[0], 
                                       timeout );
}

int parser__parser__un_marshal__sync(grpc_c_client_t *client, 
                                       grpc_c_metadata_array_t *array, uint32_t flags, 
                                       Parser__UpReq *input, Parser__UpRsp **output, 
                                       grpc_c_status_t *status, long timeout)
{
    return grpc_c_client_request_sync(client, array, flags, parser__parser__methods[1], 
                                      (void *)input, (void **)output, status, 
                                      &parser__parser__methods__funcs[1], timeout);
}

int parser__parser__un_marshal__async(grpc_c_client_t *client, 
                                        grpc_c_metadata_array_t *array, uint32_t flags, 
                                        Parser__UpReq *input, 
                                        grpc_c_client_callback_t *cb, void *tag, long timeout)
{
    return grpc_c_client_request_async(client, array, flags, parser__parser__methods[1], 
                                       input, cb, tag, &parser__parser__methods__funcs[1], 
                                       timeout );
}
